### PR TITLE
Fix linux arm64 build issue

### PR DESCRIPTION
**Pull request by MittWillson**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Why? AFAK aarch64 could not compile the WASM part.

**Comment by MittWillson** [comment]
actually, I did find *_runtime.wasm and *_runtime.compact.wasm files in the target directory, and changed this patch did suscced build in arm server and docker image with docker buildx

**Comment by HackFisher** [comment]
@MittWillson submit pull request from a branch of darwinia repo rather from a fork will help fix the ci?

Refer: https://github.com/darwinia-network/darwinia/blob/master/CONTRIBUTING.adoc

**Comment by MittWillson** [comment]
@HackFisher If confirmed this PR can be helped, I will create a new PR from branch

**Comment by AurevoirXavier** [comment]
> actually, I did find *_runtime.wasm and *_runtime.compact.wasm files in the target directory, and changed this patch did suscced build in arm server and docker image with docker buildx

You need to copy them from the target.

I'll test the aarch later.

**Comment by MittWillson** [comment]
@AurevoirXavier Do i need attach them to here?

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier Do i need attach them to here?

Nope.

Let me check if aarch64 can compile the WASM part.

**Pull request closed without merging**
