### PR TITLE
Add pre-commit git hook & bootstrap script

### LINKED ISSUE #156: Should we use cargo fmt on .githook?
https://github.com/darwinia-network/darwinia/pull/155#pullrequestreview-329962925

### PR DESCRIPTION
**Pull request by yanganto**
- add pre-commit git hook
- add bootstrap script to help people setting up
- add rustfmt test in ci
- fix #156

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Export `PATH` and remove `Color Set` (compatible with SourceTree).

```sh
#!/bin/sh

export PATH=$PATH:$HOME/.cargo/bin

rustfmt --version &>/dev/null
if [ $? != 0 ]; then
	printf "[pre_commit] rustfmt not available.\n"
	printf "[pre_commit] rustfmt can be installed via -\n"
	printf "[pre_commit] rustup component add rustfmt\n"
	exit 1
fi


problem_files=()

# first collect all the files that need reformatting
for file in $(git diff --name-only --cached); do
    if [ ${file: -3} == ".rs" ]; then
        rustfmt --check $file
        if [ $? != 0 ]; then
            problem_files+=($file)
        fi
    fi
done

if [ ${#problem_files[@]} != 0 ]; then
  # reformat the files that need it and re-stage them.
  printf "[pre_commit] Plaese format the files via -\n"
  printf "[pre_commit] cargo fmt --all\n"
  printf "[pre_commit] If you want to keep your format with special reason,\n"
  printf "[pre_commit] you can use this macro. \n"
  printf "[pre_commit] #[rustfmt::skip]\n"
  exit 1
fi

printf "[pre_commit] rustfmt\n"

exit 0
```

**Comment by AurevoirXavier** [comment]
Always failedd

```sh
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/v6/y_8scs3j797bpyn8gg0d14l00000gn/T/SourceTreeTemp.VLGTAx 
Diff in /Users/xavier/Downloads/darwinia/srml/staking/src/lib.rs at line 2027:
 			promise_month,
 		));
 
-let a = 1;
+		let a = 1;
 
 		Ok(())
 	}
[pre_commit] Plaese format the files via -
[pre_commit] cargo fmt --all
[pre_commit] If you want to keep your format with special reason,
[pre_commit] you can use this macro. 
[pre_commit] #[rustfmt::skip]
Completed with errors, see above
```

**Comment by yanganto** [comment]
The `bootstrap.sh` is test by ci environment, please check following travis report.
https://travis-ci.org/darwinia-network/darwinia/jobs/634114860?utm_medium=notification&utm_source=github_status

**Comment by yanganto** [comment]
Thanks for the review.

**Pull request merged**
