### PR TITLE
🎉🎉 CC1 -> Darwinia 🎉🎉

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
@wi1dcard Please help with checking the bootnodes.

**Comment by wi1dcard** [comment]
> @wi1dcard Please help with checking the bootnodes.

Sure I'll check out later.

**Comment by wi1dcard** [comment]
Question: isn't this be changed along in this PR?

<https://github.com/darwinia-network/darwinia/blob/1f75ad1df7e1800ef0f7683b15b60f5eb2ced1b8/node/service/src/chain_spec/darwinia.rs#L319-L323>

**Comment by AurevoirXavier** [comment]
> Question: isn't this be changed along in this PR?
> 
> https://github.com/darwinia-network/darwinia/blob/1f75ad1df7e1800ef0f7683b15b60f5eb2ced1b8/node/service/src/chain_spec/darwinia.rs#L319-L323

This won't affect the bootnodes. But better to make a change.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
