### PR TITLE
Release v0.11.8

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Review by HackFisher — APPROVED** [review]
LGTM, we do not have migration in this runtime upgrade, right?

**Comment by AurevoirXavier** [comment]
No, no migration within this update.

**Comment by AurevoirXavier** [comment]
[BOT CHECK] pre-release

**Review by AsceticBear — APPROVED** [review]
The changes LGTM!. One more thing is that the darwinia-common 0.11.8 has not been tested in pangolin. It's would be more much better to upgrade pangolin nodes firstly. That's the reason for the existence of test network.

**Pull request merged**
