### PR TITLE
Staking Module Refactor 

### LINKED ISSUE #80: Replace fraction stuffs with Permill and Perbill
https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/sr_arithmetic.rs#L518

### PR DESCRIPTION
**Pull request by HackFisher**
- Using Perbill or Perquintill to do fraction computation and clear the… pow logic, Fixed #80
- refactor and simplify the unbond and deposit claim

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
```rust
pub fn from_rational_approximation<N>(p: N, q: N) -> Self
where
    N: Clone + Ord + From<u64> + TryInto<u64> + Div<N, Output = N>, 
```

Approximate the fraction p/q into a per-thing fraction. This will never overflow.

The computation of this approximation is performed in the generic type N. Given M as the data type that can hold the maximum value of this per-thing (e.g. u32 for perbill), this can only work if N == M or N: From<M> + TryInto<M>.

---

from:

```rust
l.active_ring.saturated_into::<ExtendedBalance>() 

+ 

l.active_kton.saturated_into::<ExtendedBalance>() * Self::kton_vote_weight() / ACCURACY
```

to:

```rust
Perquintill::from_rational_approximation(
	l.active_ring.saturated_into::<ExtendedBalance>(), 
	Self::ring_pool().saturated_into::<ExtendedBalance>().max(1)
) * (POWER_COUNT / 2)

+ 

Perquintill::from_rational_approximation(
	l.active_kton.saturated_into::<ExtendedBalance>(),
	Self::kton_pool().saturated_into::<ExtendedBalance>().max(1)
) * (POWER_COUNT / 2)
```

**Comment by HackFisher** [comment]
@AurevoirXavier Any comment on the changes? Are they looks good to you?

The docuemnts are outdated, the latest version supports uint128 for Perbill and Perquintill.

**Comment by HackFisher** [comment]
> ```rust
> pub fn from_rational_approximation<N>(p: N, q: N) -> Self
> where
>     N: Clone + Ord + From<u64> + TryInto<u64> + Div<N, Output = N>, 
> ```
> 
> Approximate the fraction p/q into a per-thing fraction. This will never overflow.
> 
> The computation of this approximation is performed in the generic type N. Given M as the data type that can hold the maximum value of this per-thing (e.g. u32 for perbill), this can only work if N == M or N: From + TryInto.
> 
> from:
> 
> ```rust
> l.active_ring.saturated_into::<ExtendedBalance>() 
> 
> + 
> 
> l.active_kton.saturated_into::<ExtendedBalance>() * Self::kton_vote_weight() / ACCURACY
> ```
> 
> to:
> 
> ```rust
> Perquintill::from_rational_approximation(
> 	l.active_ring.saturated_into::<ExtendedBalance>(), 
> 	Self::ring_pool().saturated_into::<ExtendedBalance>().max(1)
> ) * (POWER_COUNT / 2)
> 
> + 
> 
> Perquintill::from_rational_approximation(
> 	l.active_kton.saturated_into::<ExtendedBalance>(),
> 	Self::kton_pool().saturated_into::<ExtendedBalance>().max(1)
> ) * (POWER_COUNT / 2)
> ```

```
     |
1125 |                 active.saturated_into::<ExtendedBalance>(),
     |                        ^^^^^^^^^^^^^^ the trait `std::convert::From<S>` is not implemented for `u128`
     |
     = help: consider adding a `where u128: std::convert::From<S>` bound
     = note: required because of the requirements on the impl of `std::convert::Into<u128>` for `S`
     = note: required because of the requirements on the impl of `std::convert::TryFrom<S>` for `u128`
     = note: required because of the requirements on the impl of `std::convert::TryInto<u128>` for `S`
     = note: required because of the requirements on the impl of `sr_api_hidden_includes_decl_storage::hidden_include::sr_primitives::traits::UniqueSaturatedInto<u128>` for `S`

```

**Comment by AurevoirXavier** [comment]
```rust
fn slashable_balance_of(stash: &T::AccountId) -> ExtendedBalance {
	// power is a mixture of ring and kton
	// power = ring_ratio * POWER_COUNT / 2 + kton_ratio * POWER_COUNT / 2
	fn calc_power<S: SaturatedConversion + rstd::convert::TryInto<u128>>(active: S, pool: S) -> ExtendedBalance {
		const HALF_POWER: u128 = 1_000_000_000 / 2;

		Perquintill::from_rational_approximation(
			active.saturated_into::<ExtendedBalance>(),
			pool.saturated_into::<ExtendedBalance>().max(1),
		) * HALF_POWER
	}

	Self::bonded(stash)
		.and_then(Self::ledger)
		.map(|l| calc_power(l.active_ring, Self::ring_pool()) + calc_power(l.active_kton, Self::kton_pool()))
		.unwrap_or_default()
}
```

We need a `TryInto<u128>` bound.

**Pull request merged**
