### PR TITLE
check storage prefix

### PR DESCRIPTION
**Pull request by fewensa**
issue: https://github.com/darwinia-network/darwinia/issues/692

### CODE REVIEW

**Comment by fewensa** [comment]
@AurevoirXavier  successfully run the node

**Comment by AurevoirXavier** [comment]
I'll make some changes.

**Comment by HackFisher** [comment]
CI failed.
```
[ci-bot/src/main.rs:18] &cli = Cli {
Spawning Local Node...
    checker: StoragePrefix(
        Checker {
            chain: Darwinia,
            exec: "./target/release/darwinia",
        },
    ),
}
[ci-bot/src/main.rs:21] e = NotSupportMetadataVersion(
    13,
)
```

**Comment by AurevoirXavier** [comment]
> CI failed.
> 
> ```
> [ci-bot/src/main.rs:18] &cli = Cli {
> Spawning Local Node...
>     checker: StoragePrefix(
>         Checker {
>             chain: Darwinia,
>             exec: "./target/release/darwinia",
>         },
>     ),
> }
> [ci-bot/src/main.rs:21] e = NotSupportMetadataVersion(
>     13,
> )
> ```

This tool is not ready yet. Once it has been done, I'll mark this PR as ready for review.

**Comment by AurevoirXavier** [comment]
Move to another PR.

**Pull request closed without merging**
