### PR TITLE
v0.10.1 Preview

### PR DESCRIPTION
**Pull request by AurevoirXavier**
https://github.com/darwinia-network/darwinia-common/pull/673

### CODE REVIEW

**Review by HackFisher — COMMENTED** [review]
LGTM. Might still need changelog update and crate bump version before git tag & new release.

- [x] Checked bump spec version
- [x] Checked cargo.lock, dependency, HeaderMMR is using frame V1: https://github.com/darwinia-network/darwinia-common/blob/e9ff1f45049108d8f9aee87fb83f16cacc37a0e9/frame/header-mmr/src/lib.rs#L157
- [x] Checked migration, Crab runtime does not have RelayerGame pallet, and Darwinia have.
- [x] Checked Storage prefix.

**Comment by AurevoirXavier** [comment]
@AsceticBear Request a review.

**Comment by HackFisher** [comment]
darwinia-common dependency changes for review and reference:

https://github.com/darwinia-network/darwinia-common/compare/darwinia-v0.10.0..xavier-darwinia-v0.10.1

**Comment by HackFisher** [comment]
cc @sxlwar  @WoeOm . Companion changes in bridger:

cc @wuminzhe @fewensa 
Release: https://github.com/darwinia-network/bridger/releases/tag/v0.3.3-3
Diff: https://github.com/darwinia-network/bridger/compare//v0.3.3-2...v0.3.3-3

**Comment by AsceticBear** [comment]
> HeaderMMR is using frame V1: https://github.com/darwinia-network/darwinia-common/blob/e9ff1f45049108d8f9aee87fb83f16cacc37a0e9/frame/header-mmr/src/lib.rs#L157

The [Migrate header-mmr to Attribute Macro](https://github.com/darwinia-network/darwinia-common/pull/613)  had done in the previous release 0.10.0, So there is no relationship with this pr?

**Comment by AurevoirXavier** [comment]
> > HeaderMMR is using frame V1: https://github.com/darwinia-network/darwinia-common/blob/e9ff1f45049108d8f9aee87fb83f16cacc37a0e9/frame/header-mmr/src/lib.rs#L157
> 
> The [Migrate header-mmr to Attribute Macro](https://github.com/darwinia-network/darwinia-common/pull/613) had done in the previous release 0.10.0, So there is no relationship with this pr?

Crab & Darwinia is on https://github.com/darwinia-network/darwinia-common/releases/tag/darwinia-v0.10.0 now.

**Review by AsceticBear — APPROVED** [review]

**Pull request merged**
