### PR TITLE
Async backing

### LINKED ISSUE #1488: Support asynchronous backing
https://wiki.polkadot.network/docs/maintain-guides-async-backing

https://forum.polkadot.network/t/paritytech-update-for-april-2024/7646

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Closes #1488.

In my post #1488, I mentioned that the Moonbeam side might require some updates. @boundless-forest

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
@boundless-forest EVM test did not pass.

**Comment by boundless-forest** [comment]
```sh
c/d/darwinia (bear-aync-backing) ▶︎︎ ./target/release/darwinia --chain pangolin-dev --tmp --alice --tracing-api debug,trace --frontier-backend-type sql
2024-05-11 15:11:40 Darwinia    
2024-05-11 15:11:40 ✌️  version 6.6.2-75f090649e9    
2024-05-11 15:11:40 ❤️  by Darwinia Network <hello@darwinia.network>, 2018-2024    
2024-05-11 15:11:40 📋 Chain specification: Pangolin2 D    
2024-05-11 15:11:40 🏷  Node name: Alice    
2024-05-11 15:11:40 👤 Role: AUTHORITY    
2024-05-11 15:11:40 💾 Database: RocksDb at /tmp/substrate3NJqLP/chains/pangolin2-d/db/full    
2024-05-11 15:11:42 Parachain id: Id(2105)    
2024-05-11 15:11:42 Parachain Account: 5Ec4AhNxga1JYLioRBNxfRnovheDELVbZTRSnKMgvSVPvNcN    
2024-05-11 15:11:42 Is collating: yes    
2024-05-11 15:11:42 [pallet::staking] assembling new collators for new session 0 at #0    
2024-05-11 15:11:42 [pallet::staking] assembling new collators for new session 1 at #0    
2024-05-11 15:11:43 🔨 Initializing Genesis block/state (state: 0xb2db…4590, header-hash: 0xbfbd…99cb)    
2024-05-11 15:11:43 📑 Connection configuration: SqliteBackendConfig { path: "/tmp/substrate3NJqLP/chains/pangolin2-d/sql/frontier.db3", create_if_missing: true, thread_count: 4, cache_size: 209715200 }    
2024-05-11 15:11:43 🏷  Local node identity is: 12D3KooWLJRYUe1FXBxCGs9X5AQoHPjFr6xRsPjrbr8xF5eZ74q8    
2024-05-11 15:11:43 Import genesis    
2024-05-11 15:11:43 💻 Operating system: linux    
2024-05-11 15:11:43 💻 CPU architecture: x86_64    
2024-05-11 15:11:43 💻 Target environment: gnu    
2024-05-11 15:11:43 💻 CPU: AMD Ryzen 7 5700G with Radeon Graphics    
2024-05-11 15:11:43 💻 CPU cores: 8    
2024-05-11 15:11:43 💻 Memory: 63578MB    
2024-05-11 15:11:43 💻 Kernel: 6.5.0-28-generic    
2024-05-11 15:11:43 💻 Linux distribution: Ubuntu 22.04.4 LTS    
2024-05-11 15:11:43 💻 Virtual machine: no    
2024-05-11 15:11:43 📦 Highest known block at #0    
2024-05-11 15:11:43 〽️ Prometheus exporter started at 127.0.0.1:9615    
2024-05-11 15:11:43 Running JSON-RPC server: addr=127.0.0.1:9944, allowed origins=["http://localhost:*", "http://127.0.0.1:*", "https://localhost:*", "https://127.0.0.1:*", "https://polkadot.js.org"]    
2024-05-11 15:11:48 🙌 Starting consensus session on top of parent 0xbfbd8f767ae7dc0acc88ed78836753d466cb2df2ba4fc813c1312ac9cedf99cb    
2024-05-11 15:11:48 panicked at /home/bear/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/c8d2251/cumulus/pallets/aura-ext/src/consensus_hook.rs:69:9:
assertion `left == right` failed: slot number mismatch
  left: Slot(285901918)
 right: Slot(0)    
2024-05-11 15:11:48 1 storage transactions are left open by the runtime. Those will be rolled back.    
2024-05-11 15:11:48 1 storage transactions are left open by the runtime. Those will be rolled back.    
2024-05-11 15:11:48 ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x4f723d - <unknown>!rust_begin_unwind
    1: 0x15920 - <unknown>!core::panicking::panic_fmt::h7a368385936888dc
    2: 0x16440 - <unknown>!core::panicking::assert_failed_inner::h8608b548c883ea8f
    3: 0x40ffbb - <unknown>!core::panicking::assert_failed::h2f0ca201fdc74f98
    4: 0x3adc40 - <unknown>!<cumulus_pallet_aura_ext::consensus_hook::FixedVelocityConsensusHook<T,_,_,_> as cumulus_pallet_parachain_system::consensus_hook::ConsensusHook>::on_state_proof::h0fc8de67199d2e47
    5: 0x237ba3 - <unknown>!frame_support::storage::transactional::with_transaction::haf25409beb434094
    6: 0x1a8a6e - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::{{closure}}::h7de027a2a3b5a249
    7: 0x1b3e69 - <unknown>!environmental::local_key::LocalKey<T>::with::ha5fe1858700802dc
    8: 0x160eb3 - <unknown>!<pangolin_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h2e7a00319cda07d7
    9: 0x155e25 - <unknown>!<pangolin_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h2cad3cd748893c87
   10: 0x4411ea - <unknown>!<fp_self_contained::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra,SelfContainedSignedInfo> as sp_runtime::traits::Applyable>::apply::h12360671c174c9d3
   11: 0x3f1be5 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h81f7d0327e18a0d6
   12: 0x1db61c - <unknown>!BlockBuilder_apply_extrinsic. Dropping.    
2024-05-11 15:11:48 panicked at /home/bear/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/c8d2251/cumulus/pallets/parachain-system/src/lib.rs:248:13:
set_validation_data inherent needs to be present in every block!    
2024-05-11 15:11:48 Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x4f723d - <unknown>!rust_begin_unwind
    1: 0x15920 - <unknown>!core::panicking::panic_fmt::h7a368385936888dc
    2: 0x4ae927 - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<<<T as frame_system::pallet::Config>::Block as sp_runtime::traits::HeaderProvider>::HeaderT as sp_runtime::traits::Header>::Number>>::on_finalize::h952e5e72e9ecc7d3
    3: 0x3b9fea - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h5bd89832c4727e0b
    4: 0x3f20ec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h77b85e4cf31b58f8
    5: 0x1db76c - <unknown>!BlockBuilder_finalize_block    
2024-05-11 15:11:48 💤 Idle (0 peers), best: #0 (0xbfbd…99cb), finalized #0 (0xbfbd…99cb), ⬇ 0 ⬆ 0   
```
There seems to be fire somewhere.

**Comment by AurevoirXavier** [comment]
I guess we need to update the `--dev` service.

**Comment by boundless-forest** [comment]
> I guess we need to update the `--dev` service.

Please help fix it so I can pallet the ts tests.

**Pull request merged**
