### PR TITLE
Support tracing for the staking `ethtx-forward` transaction

### LINKED ISSUE #1533: Failed to fetch internal transactions for blocks on darwinia tracing node.
## Darwinia blockscout log
```log
{"time":"2024-07-12T02:22:25.217Z","severity":"error","message":"failed to fetch internal transactions for blocks [2955600, 3085669, 3088379, 3088582, 3091618, 3091931, 3094042, 3094127, 3094559, 3095683, 3095708, 3096285, 3096748, 3097466, 3097908, 3097972, 3098098, 3098390, 3098981, 3098987, 3099179, 3099873, 3099977, 3099987, 3100149, 3100413, 3100580, 3100959, 3101048, 3101079]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2955600, transaction_hash: \"0xc87f178f1cea8cc0c49b05e11ed12ee612d2335e545a373a2ba49f2b6ccbc2b4\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.621Z","severity":"error","message":"failed to fetch internal transactions for blocks [2880000, 3083400, 3087008, 3090651, 3090965, 3092569, 3093433, 3094330, 3094661, 3096272, 3096440, 3096719, 3096819, 3097590, 3097616, 3097667, 3098378, 3098463, 3098532, 3099211, 3099313, 3099617, 3099621, 3100112, 3100233, 3100433, 3100728, 3100754, 3101292, 3101297]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2880000, transaction_hash: \"0x2dc02edff0cbd806885ea67f3bfbf1f26340722c49721564723f04271c872202\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.652Z","severity":"error","message":"failed to fetch internal transactions for blocks [2791800, 3086913, 3089529, 3089901, 3092686, 3092807, 3093399, 3094989, 3095217, 3095689, 3096328, 3097355, 3097577, 3097722, 3097914, 3098169, 3098350, 3098725, 3098728, 3099541, 3099553, 3099577, 3099698, 3099973, 3100221, 3100450, 3100651, 3100740, 3101013, 3101031]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2791800, transaction_hash: \"0x98054eb20085d1e361dd0b3d4326f0fa112411634c07f53682f2357721486085\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.756Z","severity":"error","message":"failed to fetch internal transactions for blocks [2934000, 3084969, 3087325, 3089903, 3091678, 3092242, 3093398, 3093913, 3095188, 3095649, 3096290, 3096949, 3097068, 3097141, 3097842, 3098163, 3098412, 3098414, 3098824, 3099027, 3099264, 3099632, 3099780, 3100070, 3100338, 3100472, 3100630, 3100791, 3100912, 3101238]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2934000, transaction_hash: \"0x439918c1b1ecfae820776a19802b84701d8d8553e7568052ef1e1172460b8a30\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.806Z","severity":"error","message":"failed to fetch internal transactions for blocks [2894400, 3076698, 3087177, 3089771, 3092241, 3092498, 3092690, 3093791, 3094953, 3095280, 3096139, 3096347, 3096853, 3097648, 3097882, 3098200, 3098275, 3098920, 3098921, 3099250, 3099604, 3099668, 3099741, 3100258, 3100551, 3100790, 3100876, 3100900, 3101203, 3101302]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2894400, transaction_hash: \"0xffc2c4d7ec27b7933cf7701dc977a3b9b1e70cd1655964adcc8817675951159f\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.937Z","severity":"error","message":"failed to fetch internal transactions for blocks [3009600, 3081373, 3086566, 3090862, 3091145, 3092111, 3092974, 3094328, 3094909, 3095588, 3095871, 3096318, 3096775, 3097594, 3097927, 3098292, 3098319, 3098488, 3099151, 3099343, 3099633, 3099766, 3099783, 3099947, 3100242, 3100421, 3100562, 3100837, 3101000, 3101086]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 3009600, transaction_hash: \"0xaa6aa887695ebed7a6f85a04c8a98146ce56e143f5c5fc268181a4e769959710\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:05.982Z","severity":"error","message":"failed to fetch internal transactions for blocks [2898000, 3074797, 3089822, 3090584, 3091093, 3092195, 3093384, 3093438, 3094393, 3095448, 3096331, 3096849, 3096927, 3097023, 3097642, 3097900, 3098593, 3098706, 3099118, 3099494, 3099538, 3099727, 3099983, 3100080, 3100339, 3100408, 3100829, 3100950, 3100958, 3101108]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2898000, transaction_hash: \"0x52c310c4f6e89c3f06cd3000ebd116223708dfc3c314f7c10f5c0dfb8525df6d\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.063Z","severity":"error","message":"failed to fetch internal transactions for blocks [3042000, 3082710, 3089437, 3089868, 3091210, 3092668, 3092757, 3093816, 3094964, 3095662, 3095673, 3096353, 3096900, 3097031, 3097510, 3098293, 3098298, 3098879, 3098918, 3099170, 3099547, 3099753, 3100046, 3100234, 3100241, 3100278, 3100725, 3100966, 3100967, 3101096]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 3042000, transaction_hash: \"0x917081012ad99d5a52754ac7038478f184dcbf3dbf5be346ec31a59bbb60ec78\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.120Z","severity":"error","message":"failed to fetch internal transactions for blocks [2802600, 3085898, 3089412, 3090004, 3091189, 3091731, 3092964, 3094020, 3094947, 3095639, 3095781, 3096685, 3097034, 3097592, 3097691, 3098053, 3098328, 3098358, 3099120, 3099324, 3099341, 3099830, 3100020, 3100134, 3100244, 3100739, 3100750, 3100806, 3100979, 3101097]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2802600, transaction_hash: \"0x8fcb9e4c0093fe0b195dd637c9d0bd8bdd8d9cea7e1776fee7764e4178619609\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.253Z","severity":"error","message":"failed to fetch internal transactions for blocks [3002400, 3082676, 3087093, 3091324, 3091771, 3092995, 3093702, 3094898, 3094971, 3095661, 3096024, 3096293, 3096834, 3097173, 3097902, 3097964, 3098063, 3098413, 3099100, 3099172, 3099232, 3099778, 3099791, 3100158, 3100495, 3100561, 3100704, 3100923, 3101183, 3101214]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 3002400, transaction_hash: \"0xd6eff11efdaa98168c49cc352626cb41cf0aa46c9cec00e0c107059242e01b4e\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.290Z","severity":"error","message":"failed to fetch internal transactions for blocks [2966400, 3082790, 3087369, 3090046, 3090930, 3092517, 3092825, 3094031, 3094399, 3095451, 3095925, 3096334, 3096990, 3097309, 3097625, 3097841, 3098049, 3098486, 3098752, 3099136, 3099426, 3099631, 3099779, 3100303, 3100383, 3100478, 3100628, 3101002, 3101020, 3101075]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2966400, transaction_hash: \"0xdcac75baea9230b0e05dfa2d60bd3603b2b69e3671dccb16a5ea63ca5d6ddee0\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.392Z","severity":"error","message":"failed to fetch internal transactions for blocks [2944800, 3078261, 3087317, 3090931, 3091462, 3092681, 3093985, 3094387, 3095136, 3095494, 3095696, 3096410, 3096911, 3097574, 3097654, 3097917, 3098217, 3098408, 3098647, 3099253, 3099308, 3099807, 3099922, 3099971, 3100267, 3100538, 3100587, 3100839, 3101042, 3101226]: ** (ErlangError) Erlang error: [%{code: -32603, data: %{block_number: 2944800, transaction_hash: \"0x49a1e511874563f7c12154c12316cdf22e1b6b0d6529f3d859f716cd3592b68b\", transaction_index: 0}, message: \"DispatchError: Other(\\\"\\\")\"}]","metadata":{"count":30,"fetcher":"internal_transaction","error_count":30}}
{"time":"2024-07-12T02:32:06.468Z","severity":"error","message":"failed to fetch internal transactions for blocks [2840400, 3080238, 3087720, 3090112, 3091739, 3092754, 3093035, 3094394, 3094403, 3095504, 3096023, 3096698, 3096982, 3097611, 3097680, 3098064, 3098331, 3098361, 3098508, 3099175, 3099191, 3099589, 30997
```

### PR DESCRIPTION
**Pull request by boundless-forest**
Fix #1533 Utilized the existing `ETHEREUM_XCM_TRACING_STORAGE_KEY` storage to achieve.

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Is it possible to put this in the ethtx-forward?

**Comment by boundless-forest** [comment]
> Is it possible to put this in the ethtx-forward?
> 
> Trace everything that goes through ethtx-forward.

It's possible. We need to integrate the `xcm-primitive` and tracer crate into the ethtx-forward pallet and manage it as a feature. I have considered this approach, debating whether it is the right way to proceed. Both approaches have their pros and cons. This PR's solution maintains the cleanliness of ethtx-forward and keeps the tracing functionality within the runtime config scope instead of the pallet. The alternative approach is more general, keeping the runtime config scope clean but potentially making ethtx-forward a bit messy.

**Comment by AurevoirXavier** [comment]
Because I believe this should belong to ethtx-forward. Otherwise, it makes the other pallet "a bit messy."

**Comment by boundless-forest** [comment]
Prefer to use #1541

**Pull request closed without merging**
