### PR TITLE
fix error while compling no_std wasm

### PR DESCRIPTION
**Pull request by hammeWang**

### CODE REVIEW

**Comment by hammeWang** [comment]
close https://github.com/darwinia-network/darwinia/issues/117

**Comment by hammeWang** [comment]
@AurevoirXavier what's your point? sorry I don't get you.

**Comment by AurevoirXavier** [comment]
@hammeWang **default** contains std, so we disable it. But we add **serialize** which contains std. `default-features = false` will be overwrited.

**Comment by hammeWang** [comment]
@AurevoirXavier yep, that's the reason `feature serailze` need to be removed.

**Pull request merged**
