### PR TITLE
Update staking precompile method

### PR DESCRIPTION
**Pull request by boundless-forest**
@JayJay1024 Please note the status of this PR, some methods selectors have changed.

### CODE REVIEW

**Review by hackfisher — APPROVED** [review]
@JayJay1024 Please be aware of these ABI changes.

**Comment by JayJay1024** [comment]
> @JayJay1024 Please be aware of these ABI changes.

Got it. Will Crab and Darwinia be upgraded at the same time?

**Comment by boundless-forest** [comment]
> Got it. Will Crab and Darwinia be upgraded at the same time?

No, Crab first, then Darwina in the past. Pay attention to the governance voting channel.

**Comment by JayJay1024** [comment]
> > Got it. Will Crab and Darwinia be upgraded at the same time?
> 
> No, Crab first, then Darwina in the past. Pay attention to the governance voting channel.

Okay

**Pull request merged**
