### PR TITLE
Release 0.6.7

### PR DESCRIPTION
**Pull request by AurevoirXavier**
- [x] Update Substrate

### CODE REVIEW

**Comment by HackFisher** [comment]
https://polkadot.network/grandpa-equivocation-and-sysinfo-process-collection-results-in-slashing-on-kusama-network-a-post-mortem/

**Comment by AurevoirXavier** [comment]
Hold on, I'll make a migration to fix the ring/kton pool.

**Comment by AurevoirXavier** [comment]
Fix slash, correct pool value.

https://github.com/darwinia-network/darwinia-common/pull/248

**Comment by HackFisher** [comment]
> 52494a465ab68904343c0525e86261ebcb166808

Cargo.lock show that substrate version is ed4f7a113073c08cba9020c3f0dd6c8f0441f857, and it seems to be newer than 52494a465ab68904343c0525e86261ebcb166808, should also works.

**Comment by AurevoirXavier** [comment]
> > 52494a465ab68904343c0525e86261ebcb166808
> 
> Cargo.lock show that substrate version is ed4f7a113073c08cba9020c3f0dd6c8f0441f857, and it seems to be newer than 52494a465ab68904343c0525e86261ebcb166808, should also works?

Yes, I'm trying to add evm on this commit. It'll be a little newer.

**Review by HackFisher — APPROVED** [review]

**Comment by HackFisher** [comment]
@AurevoirXavier LGTM, the PR is draft status, not reeady for merge now

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier LGTM, the PR is draft status, not reeady for merge now

EVM is on the way.

**Pull request merged**
