### PR TITLE
Record `proof_size` cost for precompiles

### LINKED ISSUE #1233: Record external cost for the substrate pallet based precompile
The substrate pallet based precompile introduces extra proof_size cost, this part should also be charged under the new transaction fee machenisim.

### PR DESCRIPTION
**Pull request by boundless-forest**
Close #1233

### CODE REVIEW

**Comment by AurevoirXavier** [comment]
Is this only necessary for the asset pallet?

**Comment by boundless-forest** [comment]
> precompile::view

And with DB reads or writes

**Comment by AurevoirXavier** [comment]
> > precompile::view
> 
> And with DB reads or writes

Why https://github.com/darwinia-network/darwinia/blob/bb0bffca7f2a5d643e49a64b62f8e482b90d6c81/precompile/bls12-381/src/lib.rs#L59 use `record_cost`?

**Comment by boundless-forest** [comment]
> use `record_cost`?

Nice catch. That's because this is a pure compution precompile, no db operation involved, so no extra proof_size cost there.

**Pull request merged**
