### PR TITLE
GitHub Actions builds docker image.

### PR DESCRIPTION
**Pull request by wi1dcard**
Due to the strict resource limit of DockerHub's CI, migrate the docker image build process to GitHub Actions. Also, Docker announced the rate limits per IP starting on 1st Nov. This might impact users like me who use the Docker image running Darwinia. I'd like to publish the image on [quay.io](https://quay.io) which is the provider we've already used in other projects like [darwinia-network/shadow](https://quay.io/repository/darwinia-network/apps) and [darwinia-network/apps](https://quay.io/repository/darwinia-network/apps).

The DockerHub build hasn't been removed. After the build on GitHub Actions gets stable, I'll choose a time to bring down the automated builds on Docker Hub.

BTW, this PR removed the dependency of the legacy builder image `iteringops/darwinia-builder`, cc @freehere107 think you might need to know this. If there's no other repo requiring the image, it can be deprecated at any time (I don't have the org `iteringops` permission on DockerHub).

### CODE REVIEW

**Comment by wi1dcard** [comment]
The new docker image built by GitHub Actions has been deployed on nodes of group`[KUBE-VALI] London *`, which seems working well. Plus, I've noticed a significant improvement of docker image pulling speed on London nodes using `quay.io`.

**Comment by AurevoirXavier** [comment]
Ready for review?

**Comment by wi1dcard** [comment]
> Ready for review?

Yes

**Comment by wi1dcard** [comment]
ping @AurevoirXavier @HackFisher Can we take a look at this PR?

**Review by HackFisher — APPROVED** [review]

**Comment by wi1dcard** [comment]
Would this be okay to merge?

**Pull request merged**
