### PR TITLE
Generate Version Automatically

### LINKED ISSUE #863: Use ENV to Fill the Template
Instead, modify the version manually.
Like https://github.com/darwinia-network/darwinia-parachain/blob/main/.github/release-template.md?plain=1#L17

### PR DESCRIPTION
**Pull request by AurevoirXavier**
Close #863.

### CODE REVIEW

**Review by fewensa — APPROVED** [review]

**Review by HackFisher — COMMENTED** [review]
Is this ready for review or merge? LGTM.

**Comment by AurevoirXavier** [comment]
> Is this ready for review or merge? LGTM.

Nope.
@fewensa will add another ENV to generate the runtime version.

**Comment by fewensa** [comment]
```
{
  "size": 1075488,
  "compression": {
    "size_compressed": 1075488,
    "size_decompressed": 4015046,
    "compressed": true
  },
  "reserved_meta": [
    109,
    101,
    116,
    97
  ],
  "reserved_meta_valid": true,
  "metadata_version": 14,
  "core_version": "Crab-1200 (Darwinia Crab-0.tx0.au0)",
  "proposal_hash": "0x211758019856db80521b273df16b1f2d03b0f45315e3eb452b40941074a208d2",
  "parachain_authorize_upgrade_hash": "0x630d39d8ef9b1815fefd0ec1b73e6f98a5b9ef64af23b18477efa039fec653d0",
  "ipfs_hash": "QmdTQEgoEYbrzgcYkEuFrs5e8Dd17wMxxDvbCzKFji3SnY",
  "blake2_256": "0x2baf3f495e92c9638a659071c620cfe2635c6d2aa27cd3fdf80c636e1f11c02f"
}
```


```
~$ cat crab-runtime.compact.compressed.json | jq -r .core_version
Crab-1200 (Darwinia Crab-0.tx0.au0)

~$ cat crab-runtime.compact.compressed.json | jq -r .core_version | sed "s/.*-\([0-9]*\)[ ].*/\1/g"
1200

~$ cat darwinia-runtime.compact.compressed.json | jq -r .core_version
Darwinia-1200 (Darwinia-0.tx0.au0)

~$ cat darwinia-runtime.compact.compressed.json | jq -r .core_version | sed "s/.*-\([0-9]*\)[ ].*/\1/g"
1200
```

**Comment by AurevoirXavier** [comment]
Why the name is `core_version`?
`runtime_version` sounds good to me.

**Comment by fewensa** [comment]
Same with subwasm, `runtime_version` is better. let me change it.

**Comment by AurevoirXavier** [comment]
LGTM.

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
