### PR TITLE
Toml Configuration

### PR DESCRIPTION
**Pull request by AurevoirXavier**

### CODE REVIEW

**Comment by HackFisher** [comment]
Does this pull request need to be included in next binary release?

**Comment by AurevoirXavier** [comment]
> Does this pull request need to be included in next binary release?

Compatible with 0.6.1. People who want to use this feature that they can compile from source. 

And we can release this in 0.6.2.

**Comment by AurevoirXavier** [comment]
Move to https://github.com/darwinia-network/darwinia-common/pull/154

**Comment by AurevoirXavier** [comment]
Reopen this PR in 0.6.2.

**Pull request closed without merging**
